apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-task-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-task
  endpoints:
    - interval: 10s
      port: web