apiVersion: v1
kind: Service
metadata:
  name: prometheus-task-service
  labels:
    app: prometheus-task
spec:
  selector:
    app: prometheus-task
  ports:
    - protocol: TCP
      port: 7127
      targetPort: 7127
      name: web